name: Continous Integration

on:
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 20.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install migrate and test
              run: |
                  npm install
                  npm run migrate up
                  npm run test
              env:
                CI: true
                HOST: localhost
                PORT: 3000
                PGHOST: ${{ secrets.PGHOST_TEST }}
                PGPORT: ${{ secrets.PGPORT_TEST }}
                PGUSER: ${{ secrets.PGUSER_TEST }}
                PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
                PGDATABASE: $${{ secrets.PGDATABASE_TEST }}
                ACCESS_TOKEN_KEY: secret
                REFRESH_TOKEN_KEY: terces
                ACCESS_TOKEN_AGE: 3600

